### ISSUE TITLE
read_info_histogram.sh not running on my data

### ISSUE THREAD

**Issue by limin321** [rrwick/Filtlong#16]
I try to run read_info_histogram.sh, here is my command and output, 
(base) campus-025-033:agro_3rd dklabuser$ ./read_info_histogram.sh BC05.fastq 

READ SET SUMMARY
----------------
number of reads: 0
number of bases: 0
./read_info_histogram.sh: line 28: / 2: syntax error: operand expected (error token is "/ 2")

READ LENGTHS
------------
Traceback (most recent call last):
  File "/Users/dklabuser/limin/agro_3rd/histogram.py", line 325, in <module>
    options.agg_key_value), options)
  File "/Users/dklabuser/limin/agro_3rd/histogram.py", line 151, in histogram
    max_v = max(data, key=lambda x: x.value)
ValueError: max() arg is an empty sequence

MEAN QUALITIES
--------------
Traceback (most recent call last):
  File "/Users/dklabuser/limin/agro_3rd/histogram.py", line 325, in <module>
    options.agg_key_value), options)
  File "/Users/dklabuser/limin/agro_3rd/histogram.py", line 146, in histogram
    min_v = min(data, key=lambda x: x.value)
ValueError: min() arg is an empty sequence

WINDOW QUALITIES
----------------
Traceback (most recent call last):
  File "/Users/dklabuser/limin/agro_3rd/histogram.py", line 325, in <module>
    options.agg_key_value), options)
  File "/Users/dklabuser/limin/agro_3rd/histogram.py", line 146, in histogram
    min_v = min(data, key=lambda x: x.value)
ValueError: min() arg is an empty sequence

(base) campus-025-033:agro_3rd dklabuser$ ./read_info_histogram.sh BC05.fastq 
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]

READ SET SUMMARY
----------------
number of reads: 0
number of bases: 0
./read_info_histogram.sh: line 28: / 2: syntax error: operand expected (error token is "/ 2")

Can anyone help me with this problem. your help is greatly appreciated.

**Comment by schmittel** [comment]
I'm having the same issue... Was there a solution identified?

**Comment by schmittel** [comment]
Oh I figured it out. Needs the histogram.py script - didn't see that one. And the paths need to be matched with the *.sh script.

**Comment by Tycour** [comment]
> Oh I figured it out. Needs the histogram.py script - didn't see that one. And the paths need to be matched with the *.sh script.

Hi schmittel, can you explain what you did to get this working again?

**Comment by tauanajc** [comment]
Hi @schmittel, I'm having the same issue but didn't quite understand your solution. What do you mean by 'needs the histogram.py script' and 'paths need to be matched'?  I see the histogram script in the same folder as the read_info_histogram.sh, but don't know what is missing for the latter script to work. Thanks

**Comment by bishopia** [comment]
I'm also having this issue. @tauanajc did you figure it out?
